### ISSUE TITLE
Creating directories

### ISSUE THREAD

**Issue by bdbaraban** [kai-dg/holberton-python-scripts#3]
Currently, the script is failing when it assigns `find_dir` - it pulls up an error saying `find_dir` is of type `NoneType` and does not have the element `next.element`.

Generally, the script only works for projects that require header files with prototypes. For projects involving tasks without new header files or prototypes, the script only creates the directory without the files. (ex https://intranet.hbtn.io/projects/213)

**Comment by kai-dg** [comment]
-find all h2 with "requirements"
-next_element of h2
-find string with ".h"
-set conditionals for fix

**Comment by kai-dg** [comment]
fixed with this update to holberton-project-scraper.py:  https://github.com/kai-dg/holberton-python-scripts/commit/2e5406db2d3295d18822e809ce6920331653f08b
