### ISSUE TITLE
Not making main file when 0-main.c not found.

### ISSUE THREAD

**Issue by kai-dg** [kai-dg/holberton-python-scripts#6]
Project: 0x02. C - Functions, nested loops
Link: https://intranet.hbtn.io/projects/214

Bugs:
1. Does not create main files if it cannot find -main.c in the first instance of a pretag.
2. File creation and scrapes do not match.

Maybe use regular expression "-main.c" first find and grab pre tag from there.

**Comment by bdbaraban** [comment]
Fixed in pull request Feature #7
